### PR TITLE
Insert Autonomiccs website in the README.

### PR DESCRIPTION
**Pull request by GabrielBrascher**
Updated the website at the README file.
@rafaelweingartner and @pedro-martins could you please give a feedback?
Thanks.

### CODE REVIEW

**Comment by rafaelweingartner** [comment]
there are too many commits.
Shouldn't it be only one?

**Comment by GabrielBrascher** [comment]
Yes, I am trying to fix that, only the last commit "Add autonomiccs website in the README" should be considered.

**Comment by GabrielBrascher** [comment]
@rafaelweingartner I have fIxed it.
Now this PR has one commit only, thanks.

**Comment by rafaelweingartner** [comment]
@GabrielBrascher It is still showing up another commit that it should not. Can you check it?

**Comment by GabrielBrascher** [comment]
@rafaelweingartner now it is ok.

**Pull request merged**
