### PR TITLE
Adjusts that have to be done after the functional tests

### PR DESCRIPTION
**Pull request by rafaelweingartner**
@pedro-martins, @GabrielBrascher can you review this before we merge?
These mistakes were caught during functional tests. They are a consequence of the refactoring we did in order to prepare everything to be opened.

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
LGTM based on code review.

**Comment by rafaelweingartner** [comment]
Would you like to merge now? or do we wait for @pedro-martins ?

**Comment by GabrielBrascher** [comment]
Although I don't see any issue in this PR, we could wait a bit more.

At least until the version gets closer to launch (closer than it already is); if so, we merge with just one LGTM.

**Comment by pedro-martins** [comment]
@rafaelweingartner, I saw that you remove the @params in the JavaDocs, isn't good improve the params description instead of remove them? 

Ty.

**Comment by rafaelweingartner** [comment]
@pedro-martins yeah it would be better if we improved those @param and other links descriptions. But, we were only using the auto generated by eclipse that does not add anything to the doc.
For now, I thought removing them would be better, then letting some text that does not add anything to the documentation.

**Comment by pedro-martins** [comment]
@rafaelweingartner Ok, if this will be improved in the future, I have found no more issues with the changes, LGTM.

**Pull request merged**
