### PR TITLE
Addition of Sonar project quality badges

### PR DESCRIPTION
**Pull request by rafaelweingartner**
I think that the PR title is self explanining.

### CODE REVIEW

**Comment by GabrielBrascher** [comment]
Good job @rafaelweingartner , LGTM.

**Comment by cristofolini** [comment]
@rafaelweingartner I don't mean to sound pedantic but shouldn't it say Project _status_, instead of stats? Since it only shows the current status of the checks and not any statistics...

**Comment by rafaelweingartner** [comment]
@cristofolini not at all. I agree with you.

**Comment by cristofolini** [comment]
@rafaelweingartner Perfect. LGTM.

**Pull request merged**
